namespace CoUML_app.Test.TestSamples
{
    public class Inline
    {
        public static readonly string[] ATTRIBUTES = {
            "+ _secretItem: AtributeType[1..*] = null",
            "- _secretItem: AtributeType[1..*] = 5",
            "# _secretItem: AtributeType[1..*] = \"string\"",
            "~ _secretItem: AtributeType[1..*]",
            "_secretItem: AtributeType[10] = null",
            "+ _secretItem: AtributeType[10] = 5",
            "- _secretItem: AtributeType[10] = \"string\"",
            "# _secretItem: AtributeType[10]",
            "~ _secretItem: AtributeType[*] = null",
            "_secretItem: AtributeType[*] = 5",
            "+ _secretItem: AtributeType[*] = \"string\"",
            "- _secretItem: AtributeType[*]",
            "# _secretItem: AtributeType[5..10] = null",
            "~ _secretItem: AtributeType[5..10] = 5",
            "_secretItem: AtributeType[5..10] = \"string\"",
            "+ _secretItem: AtributeType[5..10]",
            "- _secretItem: AtributeType = null",
            "# _secretItem: AtributeType = 5",
            "~ _secretItem: AtributeType = \"string\"",
            "_secretItem: AtributeType",
            "+ _secretItem: boolean[1..*] = null",
            "- _secretItem: boolean[1..*] = 5",
            "# _secretItem: boolean[1..*] = \"string\"",
            "~ _secretItem: boolean[1..*]",
            "_secretItem: boolean[10] = null",
            "+ _secretItem: boolean[10] = 5",
            "- _secretItem: boolean[10] = \"string\"",
            "# _secretItem: boolean[10]",
            "~ _secretItem: boolean[*] = null",
            "_secretItem: boolean[*] = 5",
            "+ _secretItem: boolean[*] = \"string\"",
            "- _secretItem: boolean[*]",
            "# _secretItem: boolean[5..10] = null",
            "~ _secretItem: boolean[5..10] = 5",
            "_secretItem: boolean[5..10] = \"string\"",
            "+ _secretItem: boolean[5..10]",
            "- _secretItem: boolean = null",
            "# _secretItem: boolean = 5",
            "~ _secretItem: boolean = \"string\"",
            "_secretItem: boolean",
            "+ _secretItem: Object[1..*] = null",
            "- _secretItem: Object[1..*] = 5",
            "# _secretItem: Object[1..*] = \"string\"",
            "~ _secretItem: Object[1..*]",
            "_secretItem: Object[10] = null",
            "+ _secretItem: Object[10] = 5",
            "- _secretItem: Object[10] = \"string\"",
            "# _secretItem: Object[10]",
            "~ _secretItem: Object[*] = null",
            "_secretItem: Object[*] = 5",
            "+ _secretItem: Object[*] = \"string\"",
            "- _secretItem: Object[*]",
            "# _secretItem: Object[5..10] = null",
            "~ _secretItem: Object[5..10] = 5",
            "_secretItem: Object[5..10] = \"string\"",
            "+ _secretItem: Object[5..10]",
            "- _secretItem: Object = null",
            "# _secretItem: Object = 5",
            "~ _secretItem: Object = \"string\"",
            "_secretItem: Object",
            "+ _secretItem [1..*] = null",
            "- _secretItem [1..*] = 5",
            "# _secretItem [1..*] = \"string\"",
            "~ _secretItem [1..*]",
            "_secretItem [10] = null",
            "+ _secretItem [10] = 5",
            "- _secretItem [10] = \"string\"",
            "# _secretItem [10]",
            "~ _secretItem [*] = null",
            "_secretItem [*] = 5",
            "+ _secretItem [*] = \"string\"",
            "- _secretItem [*]",
            "# _secretItem [5..10] = null",
            "~ _secretItem [5..10] = 5",
            "_secretItem [5..10] = \"string\"",
            "+ _secretItem [5..10]",
            "- _secretItem = null",
            "# _secretItem = 5",
            "~ _secretItem = \"string\"",
            "_secretItem",
            "+ _secretItem: AtributeType[1..*] = null { uniqe, ordered}",
            "- _secretItem: AtributeType[1..*] = 5 { uniqe, ordered}",
            "# _secretItem: AtributeType[1..*] = \"string\" { uniqe, ordered}",
            "~ _secretItem: AtributeType[1..*] { uniqe, ordered}",
            "_secretItem: AtributeType[10] = null { uniqe, ordered}",
            "+ _secretItem: AtributeType[10] = 5 { uniqe, ordered}",
            "- _secretItem: AtributeType[10] = \"string\" { uniqe, ordered}",
            "# _secretItem: AtributeType[10] { uniqe, ordered}",
            "~ _secretItem: AtributeType[*] = null { uniqe, ordered}",
            "_secretItem: AtributeType[*] = 5 { uniqe, ordered}",
            "+ _secretItem: AtributeType[*] = \"string\" { uniqe, ordered}",
            "- _secretItem: AtributeType[*] { uniqe, ordered}",
            "# _secretItem: AtributeType[5..10] = null { uniqe, ordered}",
            "~ _secretItem: AtributeType[5..10] = 5 { uniqe, ordered}",
            "_secretItem: AtributeType[5..10] = \"string\" { uniqe, ordered}",
            "+ _secretItem: AtributeType[5..10] { uniqe, ordered}",
            "- _secretItem: AtributeType = null { uniqe, ordered}",
            "# _secretItem: AtributeType = 5 { uniqe, ordered}",
            "~ _secretItem: AtributeType = \"string\" { uniqe, ordered}",
            "_secretItem: AtributeType { uniqe, ordered}",
            "+ _secretItem: boolean[1..*] = null { uniqe, ordered}",
            "- _secretItem: boolean[1..*] = 5 { uniqe, ordered}",
            "# _secretItem: boolean[1..*] = \"string\" { uniqe, ordered}",
            "~ _secretItem: boolean[1..*] { uniqe, ordered}",
            "_secretItem: boolean[10] = null { uniqe, ordered}",
            "+ _secretItem: boolean[10] = 5 { uniqe, ordered}",
            "- _secretItem: boolean[10] = \"string\" { uniqe, ordered}",
            "# _secretItem: boolean[10] { uniqe, ordered}",
            "~ _secretItem: boolean[*] = null { uniqe, ordered}",
            "_secretItem: boolean[*] = 5 { uniqe, ordered}",
            "+ _secretItem: boolean[*] = \"string\" { uniqe, ordered}",
            "- _secretItem: boolean[*] { uniqe, ordered}",
            "# _secretItem: boolean[5..10] = null { uniqe, ordered}",
            "~ _secretItem: boolean[5..10] = 5 { uniqe, ordered}",
            "_secretItem: boolean[5..10] = \"string\" { uniqe, ordered}",
            "+ _secretItem: boolean[5..10] { uniqe, ordered}",
            "- _secretItem: boolean = null { uniqe, ordered}",
            "# _secretItem: boolean = 5 { uniqe, ordered}",
            "~ _secretItem: boolean = \"string\" { uniqe, ordered}",
            "_secretItem: boolean { uniqe, ordered}",
            "+ _secretItem: Object[1..*] = null { uniqe, ordered}",
            "- _secretItem: Object[1..*] = 5 { uniqe, ordered}",
            "# _secretItem: Object[1..*] = \"string\" { uniqe, ordered}",
            "~ _secretItem: Object[1..*] { uniqe, ordered}",
            "_secretItem: Object[10] = null { uniqe, ordered}",
            "+ _secretItem: Object[10] = 5 { uniqe, ordered}",
            "- _secretItem: Object[10] = \"string\" { uniqe, ordered}",
            "# _secretItem: Object[10] { uniqe, ordered}",
            "~ _secretItem: Object[*] = null { uniqe, ordered}",
            "_secretItem: Object[*] = 5 { uniqe, ordered}",
            "+ _secretItem: Object[*] = \"string\" { uniqe, ordered}",
            "- _secretItem: Object[*] { uniqe, ordered}",
            "# _secretItem: Object[5..10] = null { uniqe, ordered}",
            "~ _secretItem: Object[5..10] = 5 { uniqe, ordered}",
            "_secretItem: Object[5..10] = \"string\" { uniqe, ordered}",
            "+ _secretItem: Object[5..10] { uniqe, ordered}",
            "- _secretItem: Object = null { uniqe, ordered}",
            "# _secretItem: Object = 5 { uniqe, ordered}",
            "~ _secretItem: Object = \"string\" { uniqe, ordered}",
            "_secretItem: Object { uniqe, ordered}",
            "+ _secretItem [1..*] = null { uniqe, ordered}",
            "- _secretItem [1..*] = 5 { uniqe, ordered}",
            "# _secretItem [1..*] = \"string\" { uniqe, ordered}",
            "~ _secretItem [1..*] { uniqe, ordered}",
            "_secretItem [10] = null { uniqe, ordered}",
            "+ _secretItem [10] = 5 { uniqe, ordered}",
            "- _secretItem [10] = \"string\" { uniqe, ordered}",
            "# _secretItem [10] { uniqe, ordered}",
            "~ _secretItem [*] = null { uniqe, ordered}",
            "_secretItem [*] = 5 { uniqe, ordered}",
            "+ _secretItem [*] = \"string\" { uniqe, ordered}",
            "- _secretItem [*] { uniqe, ordered}",
            "# _secretItem [5..10] = null { uniqe, ordered}",
            "~ _secretItem [5..10] = 5 { uniqe, ordered}",
            "_secretItem [5..10] = \"string\" { uniqe, ordered}",
            "+ _secretItem [5..10] { uniqe, ordered}",
            "- _secretItem = null { uniqe, ordered}",
            "# _secretItem = 5 { uniqe, ordered}",
            "~ _secretItem = \"string\" { uniqe, ordered}",
            "_secretItem { uniqe, ordered}",
        };
        public static readonly string[] OPPERATION = {
            " + function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) ",
            " - function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) ",
            " # function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) ",
            " ~ function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) ",
            " function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) ",
            " + function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) { uniqe, ordered} ",
            " - function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) { uniqe, ordered} ",
            " # function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) { uniqe, ordered} ",
            " ~ function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) { uniqe, ordered} ",
            " function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) { uniqe, ordered} ",
            " + function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void ",
            " - function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void ",
            " # function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void ",
            " ~ function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void ",
            " function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void ",
            " + function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void { uniqe, ordered} ",
            " - function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void { uniqe, ordered} ",
            " # function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void { uniqe, ordered} ",
            " ~ function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void { uniqe, ordered} ",
            " function (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : void { uniqe, ordered} ",
            " + MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " - MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " # MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " ~ MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " + MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " - MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " # MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " ~ MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " + MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " - MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " # MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " ~ MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean ",
            " + MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " - MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " # MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " ~ MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " MoreComplexFunction (somethingA: typeA, somthingB: typeB, somethingC: typeC, somthingD:TypeD) : boolean { uniqe, ordered} ",
            " + function ( something) ",
            " - function ( something) ",
            " # function ( something) ",
            " ~ function ( something) ",
            " function ( something) ",
            " + function ( something) { uniqe, ordered} ",
            " - function ( something) { uniqe, ordered} ",
            " # function ( something) { uniqe, ordered} ",
            " ~ function ( something) { uniqe, ordered} ",
            " function ( something) { uniqe, ordered} ",
            " + function ( something) : void ",
            " - function ( something) : void ",
            " # function ( something) : void ",
            " ~ function ( something) : void ",
            " function ( something) : void ",
            " + function ( something) : void { uniqe, ordered} ",
            " - function ( something) : void { uniqe, ordered} ",
            " # function ( something) : void { uniqe, ordered} ",
            " ~ function ( something) : void { uniqe, ordered} ",
            " function ( something) : void { uniqe, ordered} ",
            " + function () ",
            " - function () ",
            " # function () ",
            " ~ function () ",
            " function () ",
            " + function () { uniqe, ordered} ",
            " - function () { uniqe, ordered} ",
            " # function () { uniqe, ordered} ",
            " ~ function () { uniqe, ordered} ",
            " function () { uniqe, ordered} ",
            " + function () : void ",
            " - function () : void ",
            " # function () : void ",
            " ~ function () : void ",
            " function () : void ",
            " + function () : void { uniqe, ordered} ",
            " - function () : void { uniqe, ordered} ",
            " # function () : void { uniqe, ordered} ",
            " ~ function () : void { uniqe, ordered} ",
            " function () : void { uniqe, ordered} "
        };
    }
}